config/routes.rb
Rails.application.routes.draw do

  root 'order_food#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :order_food

end

app/models/order_food.rb
class OrderFood < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/order_food_controller.rb
class OrderFoodController < ApplicationController
  protect_from_forgery with: :exception

  def index

  end

  def show
    @order_food = OrderFood.find(params[:id])
  end

  def new

  end

  def create
    #render plain: params[:order_food].inspect
    @order_food = OrderFood.new(food_order_params)
    response = send_food_order_to_dc_api(@order_food)
    if response
      @order_food.save
      redirect_to @order_food
    end
  rescue StandardError => e
    render plain: {
        error: e
    }, status: :unprocessable_entity
  end

  private def food_order_params
    params.require(:order_food).permit(:body)
  end

  private def send_food_order_to_dc_api(order_food)
    request_sender_service = RequestSenderService.new
    json_parser_service = JsonParserService.new
    request_sender_service.post(json_parser_service.parse_json(order_food))
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'This is the about page'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_food_helper.rb
module OrderFoodHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/index.html.erb
<h1>Index</h1>


<form class="nifty_form" action="/process/" accept-charset="UTF-8" data-remote="true" method="post">
  <input type="hidden" name="authenticity_token" value="NRkFyRWxdYNfUg7vYxLOp2SLf93lvnl+QwDWorR42Dp6yZXPhHEb6arhDOIWcqGit8jfnrPwL781/xlrzj63TA=="/>
  <input type="text" name="article[title]" id="article_title"/>
  <textarea name="article[body]" id="myTextArea" cols=100 rows=50>
  {
    "id": 9987071,
    "store_id": 282,
    "date_created": "2019-06-24T16:45:32.000-04:00",
    "date_closed": "2019-06-24T16:45:35.000-04:00",
    "last_updated": "2019-06-25T13:26:49.000-04:00",
    "total_amount": 49.9,
    "total_shipping": 5.14,
    "total_amount_with_shipping": 55.04,
    "paid_amount": 55.04,
    "expiration_date": "2019-07-22T16:45:35.000-04:00",
    "total_shipping": 5.14,
    "order_items": [
      {
        "item": {
          "id": "IT4801901403",
          "title": "Produto de Testes"
        },
        "quantity": 1,
        "unit_price": 49.9,
        "full_unit_price": 49.9
      }
    ],
    "payments": [
      {
        "id": 12312313,
        "order_id": 9987071,
        "payer_id": 414138,
        "installments": 1,
        "payment_type": "credit_card",
        "status": "paid",
        "transaction_amount": 49.9,
        "taxes_amount": 0,
        "shipping_cost": 5.14,
        "total_paid_amount": 55.04,
        "installment_amount": 55.04,
        "date_approved": "2019-06-24T16:45:35.000-04:00",
        "date_created": "2019-06-24T16:45:33.000-04:00"
      }
    ],
    "shipping": {
      "id": 43444211797,
      "shipment_type": "shipping",
      "date_created": "2019-06-24T16:45:33.000-04:00",
      "receiver_address": {
        "id": 1051695306,
        "address_line": "Rua Fake de Testes 3454",
        "street_name": "Rua Fake de Testes",
        "street_number": "3454",
        "comment": "teste",
        "zip_code": "85045020",
        "city": {
          "name": "Cidade de Testes"
        },
        "state": {
          "name": "São Paulo"
        },
        "country": {
          "id": "BR",
          "name": "Brasil"
        },
        "neighborhood": {
          "id": null,
          "name": "Vila de Testes"
        },
        "latitude": -23.629037,
        "longitude": -46.712689,
        "receiver_phone": "41999999999"
      }
    },
    "status": "paid",
    "buyer": {
      "id": 136226073,
      "nickname": "JOHN DOE",
      "email": "john@doe.com",
      "phone": {
        "area_code": 41,
        "number": "999999999"
      },
      "first_name": "John",
      "last_name": "Doe",
      "billing_info": {
        "doc_type": "CPF",
        "doc_number": "09487965477"
      }
    }
  }
  </textarea>
  <br/>
  <button onclick="prettyPrint()">Pretty Print</button>
  <button onclick="">Send</button>
  <input type="submit" name="commit" value="Create" data-disable-with="Create"/>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestDevBackend</title>
  <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <div class="row">
      <div class="logo col-md-6">Test Dev Backend - DeliveryCenter</div>
      <div class="menu col-md-6">
        <ul class="main-nav js--main-nav">
          <li><%= link_to "Home", home_path %></li>
          <li><%= link_to "Order Food", new_order_food_path %></li>
          <li><%= link_to "Sign up", about_path %></li>
        </ul>
        <a class="mobile-nav-icon js--nav-icon"><i class="ion-navicon-round"></i></a>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</header>
</body>
</html>

app/views/order_food/index.html.erb
<div class="hero-text-box">
  <h1>Lorem ipsum quam est, nisl..<br>Hello meals.</h1>
  <%= link_to "I'm hungry", new_order_food_path, :class => "btn btn-full js--scroll-to-plans" %>
</div>

app/views/order_food/new.html.erb
<h1 class="display-6">Order Food</h1>
<p class="lead">
  <i>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</i>
</p>
<%= form_for :order_food, url: "/order_food/" do |f| %>
  <div class="form-group">
    <%= f.text_area(:body, {:id => 'input-body', :class => 'form-control', :size => "100x13", :value => '{
    "id": 9987071,
    "store_id": 282,
    "date_created": "2019-06-24T16:45:32.000-04:00",
    "date_closed": "2019-06-24T16:45:35.000-04:00",
    "last_updated": "2019-06-25T13:26:49.000-04:00",
    "total_amount": 49.9,
    "total_shipping": 5.14,
    "total_amount_with_shipping": 55.04,
    "paid_amount": 55.04,
    "expiration_date": "2019-07-22T16:45:35.000-04:00",
    "total_shipping": 5.14,
    "order_items": [
      {
        "item": {
          "id": "IT4801901403",
          "title": "Produto de Testes"
        },
        "quantity": 1,
        "unit_price": 49.9,
        "full_unit_price": 49.9
      }
    ],
    "payments": [
      {
        "id": 12312313,
        "order_id": 9987071,
        "payer_id": 414138,
        "installments": 1,
        "payment_type": "credit_card",
        "status": "paid",
        "transaction_amount": 49.9,
        "taxes_amount": 0,
        "shipping_cost": 5.14,
        "total_paid_amount": 55.04,
        "installment_amount": 55.04,
        "date_approved": "2019-06-24T16:45:35.000-04:00",
        "date_created": "2019-06-24T16:45:33.000-04:00"
      }
    ],
    "shipping": {
      "id": 43444211797,
      "shipment_type": "shipping",
      "date_created": "2019-06-24T16:45:33.000-04:00",
      "receiver_address": {
        "id": 1051695306,
        "address_line": "Rua Fake de Testes 3454",
        "street_name": "Rua Fake de Testes",
        "street_number": "3454",
        "comment": "teste",
        "zip_code": "85045020",
        "city": {
          "name": "Cidade de Testes"
        },
        "state": {
          "name": "São Paulo"
        },
        "country": {
          "id": "BR",
          "name": "Brasil"
        },
        "neighborhood": {
          "id": null,
          "name": "Vila de Testes"
        },
        "latitude": -23.629037,
        "longitude": -46.712689,
        "receiver_phone": "41999999999"
      }
    },
    "status": "paid",
    "buyer": {
      "id": 136226073,
      "nickname": "JOHN DOE",
      "email": "john@doe.com",
      "phone": {
        "area_code": 41,
        "number": "999999999"
      },
      "first_name": "John",
      "last_name": "Doe",
      "billing_info": {
        "doc_type": "CPF",
        "doc_number": "09487965477"
      }
    }
  }'}) %>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.submit({:class => 'btn btn-primary'}) %>
    </div>
    <div class="form-group col-md-6 text-right">
      <%= button_tag 'Prettify JSON', {type: 'button', class: "btn btn-link btn-sm", onclick: "prettyPrint()"} %>
    </div>
  </div>
<% end %>

app/views/order_food/show.html.erb
<div class="hero-text-box">
  <% if @order_food %>
    <h1>Your order has been successfully processed!<br>Order Id: <%= @order_food.id %>.</h1>
    <%= link_to "Still hungry?", new_order_food_path, :class => "btn btn-full js--scroll-to-plans" %>
  <% else %>
    <h1>Oops, an error occured!.</h1>
    <%= link_to "Try again?", new_order_food_path, :class => "btn btn-full js--scroll-to-plans" %>
  <% end %>
</div>

app/views/pages/about.html.erb
<div class="hero-text-box">
  <h1><%= @title %></h1>
  <p><%= @content %></p>
</div>